controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\HomeController::index

listSubscriptions:
    path: /subscriptions
    methods: GET
    controller: App\Controller\SubscriptionsController::list

addSubscriptions:
    path: /subscription
    methods: POST
    controller: App\Controller\SubscriptionsController::add