controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\HomeController::index

listSubscriptions:
    path: /subscriptions
    methods: GET
    controller: App\Controller\SubscriptionsController::list

createSubscription:
    path: /subscription
    methods: POST
    controller: App\Controller\SubscriptionsController::create

readSubscription:
    path: /subscription/{id}
    methods: GET
    controller: App\Controller\SubscriptionsController::read

updateSubscription:
    path: /subscription/{id}
    methods: PUT
    controller: App\Controller\SubscriptionsController::update



listPaymentTypes:
    path: /paymentTypes
    methods: GET
    controller: App\Controller\PaymentTypeController::list

createPaymentType:
    path: /paymentType
    methods: POST
    controller: App\Controller\PaymentTypeController::create

readPaymentType:
    path: /paymentType
    methods: GET
    controller: App\Controller\PaymentTypeController::read

updatePaymentType:
    path: /paymentType/{id}
    methods: PUT
    controller: App\Controller\PaymentTypeController::update

deletePaymentType:
    path: /paymentType
    methods: DELETE
    controller: App\Controller\PaymentTypeController::add