controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\HomeController::index

listSubscriptions:
    path: /subscriptions
    methods: GET
    controller: App\Controller\SubscriptionsController::list

newSubscription:
    path: /subscription/new
    methods: GET
    controller: App\Controller\SubscriptionsController::new

saveNewSubscription:
    path: /subscription/new
    methods: POST
    controller: App\Controller\SubscriptionsController::new

detailSubscription:
    path: /subscription/{id}
    methods: GET
    controller: App\Controller\SubscriptionsController::detail

updateSubscription:
    path: /subscription/{id}
    methods: POST
    controller: App\Controller\SubscriptionsController::detail



listPaymentTypes:
    path: /paymentTypes
    methods: GET
    controller: App\Controller\PaymentTypeController::list

createPaymentType:
    path: /paymentType
    methods: POST
    controller: App\Controller\PaymentTypeController::create

readPaymentType:
    path: /paymentType/{id}
    methods: GET
    controller: App\Controller\PaymentTypeController::read

updatePaymentType:
    path: /paymentType/{id}
    methods: PUT
    controller: App\Controller\PaymentTypeController::update

deletePaymentType:
    path: /paymentType
    methods: DELETE
    controller: App\Controller\PaymentTypeController::add


